# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'testVideoDemo' do
    use_frameworks!
    pod 'TKVideoPlanet',:path => './'      # 指定路径
end


